ad1:
	ifort -I/usr/local/Cellar/netcdf/4.6.1_4/include -L/usr/local/Cellar/netcdf/4.6.1_4/lib -lnetcdf -lnetcdff ad1.f90 -o ad1

ad2:
	ifort -I/usr/local/Cellar/netcdf/4.6.1_4/include -L/usr/local/Cellar/netcdf/4.6.1_4/lib -lnetcdf -lnetcdff ad2.f90 -o ad2

ab:
	ifort -I/usr/local/Cellar/netcdf/4.6.1_4/include -L/usr/local/Cellar/netcdf/4.6.1_4/lib -lnetcdf -lnetcdff ab.f90 -o ab
